#!/bin/sh

case $BLOCK_BUTTON in
	3) setsid -f "$TERMINAL" -e nmtui
esac

[ "$( cat /sys/class/net/e*/operstate 2>/dev/null )" = 'up' ] && 
echo "󰇧 |" && exit ||
[ "$( cat /sys/class/net/w*/operstate 2>/dev/null )" = 'up' ] &&
echo "󰇧 $(awk '/^\s*w/ {print int($3 * 100 / 70) "%|"}' /proc/net/wireless)" && exit ||
[ "$( cat /sys/class/net/w*/flags 2>/dev/null )" = '0x1003' ] &&
echo "󱐅 No Network|" && exit ||
echo "󱐅 No Internet|"
